version: "3.8"
services:

  db:
    image: mariadb:10.11
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASS}
    volumes:
      - ./dbdata:/var/lib/mysql

  web:
    image: moodlehq/moodle-php-apache:8.2
    restart: unless-stopped
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/moodledata
      - ./php-ini-overrides/zend-exception.ini:/usr/local/etc/php/conf.d/99-zend-exception.ini
      - ./php-ini-overrides/opcache.ini:/usr/local/etc/php/conf.d/10-opcache.ini

    depends_on:
      - db
